### ISSUE TITLE
Which Assembly?

### ISSUE THREAD

**Issue by catb0t** [exercism/xnasm#10]
There are a lot of assembly languages and platforms. The most widely used by far and away is Intel 80x86. The easiest Assembly language to learn, from personal experience, is likely [the Netwide Assembler](http://nasm.us). There's also [the Flat Assembler](http://flatassembler.net), MIPS, ARM Assembly, etc, etc. 

If it doesn't really matter, then that's okay too (and I perhaps worry too much). But, Assembly is one of the only vague categories on the [languages page](http://exercism.io/languages), because it's pretty cut-and-dry exactly what all the others are.

If NASM is the preferred platform, then perhaps the icon can be the NASM logo, but if no particular platform will be given, then something generic might suffice.

Throughts?

**Comment by kytrinyx** [comment]
I don't recall who asked me for this one, and my guess is that they had a specific one in mind. Let's pick the simplest one and change the name and slug (and the name of the repository). E.g.

- `nasm`
- `The Netwide Assembler`
- `github.com/exercism/xnasm`

What do you think?

**Comment by catb0t** [comment]
Yes, I like that. :)

**Comment by kytrinyx** [comment]
Cool. On it :)

**Comment by kytrinyx** [comment]
http://x.exercism.io/v3/tracks/nasm
